{
    "code": 500,
    "message": "An unexpected error occurred: Expected a string value",
    "data": {
        "inputs": {
            "email": "test@example.com",
            "password": "testpassword"
        },
        "traceback": "Traceback (most recent call last):\n File \"/home/site/wwwroot/api/api_utils.py\", line 11, in wrapper\n return route_handler(req)\n ^^^^^^^^^^^^^^^^^^\n File \"/home/site/wwwroot/api/authentication.py\", line 52, in signin\n access_token, refresh_token = generate_tokens(user.user_id)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File \"/home/site/wwwroot/core/security.py\", line 30, in generate_tokens\n access_token = jwt.encode(access_token_payload, os.getenv(\"JWT_SECRET\"), algorithm='HS256')\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File \"/home/site/wwwroot/.python_packages/lib/site-packages/jwt/api_jwt.py\", line 73, in encode\n return api_jws.encode(\n ^^^^^^^^^^^^^^^\n File \"/home/site/wwwroot/.python_packages/lib/site-packages/jwt/api_jws.py\", line 160, in encode\n key = alg_obj.prepare_key(key)\n ^^^^^^^^^^^^^^^^^^^^^^^^\n File \"/home/site/wwwroot/.python_packages/lib/site-packages/jwt/algorithms.py\", line 265, in prepare_key\n key_bytes = force_bytes(key)\n ^^^^^^^^^^^^^^^^\n File \"/home/site/wwwroot/.python_packages/lib/site-packages/jwt/utils.py\", line 22, in force_bytes\n raise TypeError(\"Expected a string value\")\nTypeError: Expected a string value\n",
        "error": "Expected a string value"
    }
}